### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by polarathene** [hardware/adminer#1]
Since your dockerfile is pulling in a specific theme, would it make sense to pull in all the css themes hosted on the repo and use an ENV variable to apply the adminer.css file when starting the container up? The official docker image offers theme selection(haven't checked how it's approached). I don't imagine it to bloat file size much?

A similar image for adminer on alpine is [here](https://github.com/dockette/adminer), they're about 5MB smaller afaik, also lack the theme support but have raised it as an issue to resolve.

**Comment by hardware** [comment]
I can add a build-time variable if you want. You'll be able to use args like this :

```yml

# docker-compose.yml
adminer:
  build:
    context: https://github.com/hardware/adminer
    args:
      - THEME=haeckel
```

**Comment by hardware** [comment]
Added. Commit : c9d3ed017b16f9b139ecfefca527cdf1a6054790
